sudo: false
language: python
python:
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
addons:
  apt:
    sources:
    packages:
      - build-essential
      - pandoc
      - figlet
      - graphviz
before_install:
 - sudo apt-get update -qq
 - sudo apt-get install -y build-essential pandoc figlet graphviz
# command to install dependencies
install:
  - pip install .
  - pip install -r ./testlib/test_reqs.txt
# command to run tests
script:
    - python ./test_sake.py
    - cd functests/test3/ && python ./functest.py
